export const routesDummyData = [
  {
    _id: '1',
    title: 'Dashboard',
    path: 'dashboard',
    icon: 'ic_dashboard',
    parent: '',
    add: false,
    view: false,
    edit: false,
    remove: false,
    status: false,
  },
  {
    _id: '2',
    title: 'Role',
    path: 'role',
    icon: 'master',
    parent: 'Master',
    add: false,
    view: false,
    edit: false,
    remove: false,
    status: false,
  },
];
